import { NextResponse } from "next/server";
import { redis, relayConfigured, KEYS } from "../upstash";

// Per-question progress. The /ask page polls this while its answer request is in
// flight, so a visitor can see whether their question is waiting behind others or
// actually being written — rather than staring at a spinner for 20 seconds.

export const revalidate = 0;

export async function GET(req: Request) {
  const id = new URL(req.url).searchParams.get("id") ?? "";
  // ids are generated by the browser, so treat them as untrusted input: only ever
  // interpolate something that looks like a uuid into a key name.
  if (!/^[0-9a-f-]{8,64}$/i.test(id)) {
    return NextResponse.json({ state: "unknown" });
  }
  if (!relayConfigured()) {
    return NextResponse.json({ state: "offline" });
  }

  try {
    const raw = await redis(["GET", KEYS.progress(id)], 4000);
    if (!raw) {
      // No state yet: the node has not picked it up, so it is still in line —
      // and only now is the queue depth worth a second command.
      const depth = await redis(["LLEN", KEYS.jobs], 4000);
      const ahead = typeof depth === "number" ? depth : Number(depth ?? 0) || 0;
      return NextResponse.json({ state: "queued", ahead });
    }
    const p = JSON.parse(String(raw)) as { state?: string; via?: string; ms?: number };
    return NextResponse.json({
      state: p.state ?? "queued",
      via: p.via ?? null,
      ms: p.ms ?? null,
      ahead: 0,
    });
  } catch {
    return NextResponse.json({ state: "unknown" });
  }
}
